language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0.0"

install:
  - composer install --no-interaction --prefer-source

script: vendor/bin/phpunit