language: php

php:
  - 7.0
  - 7.1

install:
  - composer clear-cache
  - composer global require fxp/composer-asset-plugin
  - composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit